### ISSUE TITLE
换成dubbo3以后，消费者接收的消息里面全部为乱码  如何解决呢？

### ISSUE THREAD

**Issue by lifeixiang027** [linux-china/dubbo3#10]
java.lang.Exception: Dubbo client can not supported string message:  sswordorganizationNameemaidisableddisplayTypedisplayIdentifierpersistInftypeIconfSYS_ADMIN绯荤粺绠＄悊鍛楴鍖椾含鍑攼杩滄櫙绉戞妧鏈夐檺鍏徃SYS_ADMINF鐢ㄦ埛0(绯荤粺绠＄悊鍛� (SYS_ADMIN: 鍖椾含鍑攼杩滄櫙绉戞妧鏈夐檺鍏徃)

.......

	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:180)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by linux-china** [comment]
能否使用本代码中提供的样例测试一下，我测试都可以的。 同时能否查一下Java的乱码问题？

**Comment by chenlushun** [comment]
@lifeixiang027 这个问题呢，我之前有遇到过，后来我把本地相关的alibaba的jar全部删掉，并重新打包下就OK了，你可以试试看

**Comment by linux-china** [comment]
能否检查一下是否是jar包冲突。
