### ISSUE TITLE
消费者报错

### ISSUE THREAD

**Issue by shenzhuan** [linux-china/dubbo3#12]
2017-05-06 10:36:54.090 WARN [] [Slf4jLogger:54] -  [DUBBO] ReferenceConfig(null) is not DESTROYED when FINALIZE, dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.56.1
2017-05-06 10:36:54.090 WARN [] [Slf4jLogger:54] -  [DUBBO] ReferenceConfig(null) is not DESTROYED when FINALIZE, dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.56.1
2017-05-06 10:36:54.090 WARN [] [Slf4jLogger:54] -  [DUBBO] ReferenceConfig(null) is not DESTROYED when FINALIZE, dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.56.1

**Comment by shenzhuan** [comment]
2017-05-06 10:52:19.775 ERROR [] [Slf4jLogger:74] -  [DUBBO] Dubbo client can not supported string message: 0480/TB2uvYloVXXXXXXXpXXXXXXXXXX_!!2541510480.png" class="" width="1362" height="582" style="border: 0px; vertical-align: top;"/><img align="absmiddle" src="https://img.alicdn.com/imgextra/i4/2541510480/TB2wCvsoVXXXXbWXXXXXXXXXXXX_!!2541510480.png" class="" width="1364" height="610" style="border: 0px; vertical-align: top;"/><img align="absmiddle" src="https://img.alicdn.com/imgextra/i1/2541510480/TB2xd2noVXXXXcOXXXXXXXXXXXX_!!2541510480.png" class="" width="1363" height="592 in channel: NettyChannel [channel=[id: 0x6d6973d9, L:/192.168.56.1:51627 - R:/192.168.56.1:20881]], url: dubbo://192.168.56.1:20881/com.zscat.goods.service.ProductClassService?anyhost=true&application=zscat-web&check=false&codec=dubbo&dubbo=3.0.0-SNAPSHOT&generic=false&heartbeat=60000&interface=com.zscat.goods.service.ProductClassService&methods=selectPage,select,insertSelective,insertList,updateByPrimaryKeySelective,delete,insertOrUpdate,selectOne,selectByPrimaryKey,selectCount,deleteByPrimaryKey&pid=9544&realport=20881&side=consumer&timeout=0&timestamp=1494038175537, dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.56.1
java.lang.Exception: Dubbo client can not supported string message: 0480/TB2uvYloVXXXXXXXpXXXXXXXXXX_!!2541510480.png" class="" width="1362" height="582" style="border: 0px; vertical-align: top;"/><img align="absmiddle" src="https://img.alicdn.com/imgextra/i4/2541510480/TB2wCvsoVXXXXbWXXXXXXXXXXXX_!!2541510480.png" class="" width="1364" height="610" style="border: 0px; vertical-align: top;"/><img align="absmiddle" src="https://img.alicdn.com/imgextra/i1/2541510480/TB2xd2noVXXXXcOXXXXXXXXXXXX_!!2541510480.png" class="" width="1363" height="592 in channel: NettyChannel [channel=[id: 0x6d6973d9, L:/192.168.56.1:51627 - R:/192.168.56.1:20881]], url: dubbo://192.168.56.1:20881/com.zscat.goods.service.ProductClassService?anyhost=true&application=zscat-web&check=false&codec=dubbo&dubbo=3.0.0-SNAPSHOT&generic=false&heartbeat=60000&interface=com.zscat.goods.service.ProductClassService&methods=selectPage,select,insertSelective,insertList,updateByPrimaryKeySelective,delete,insertOrUpdate,selectOne,selectByPrimaryKey,selectCount,deleteByPrimaryKey&pid=9544&realport=20881&side=consumer&timeout=0&timestamp=1494038175537
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:180) [dubbo-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52) [dubbo-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82) [dubbo-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
